apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: mlops
type: Opaque
stringData:
  PG_DSN: postgresql://mlops_user:mlops_pass_2026@postgres-service.mlops.svc.cluster.local:5432/mlops
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
